#!/bin/bash
#
# FreaknAwesomePrompt
# with some git magic included
#
# credits:
#  - google
#  - man bash
#  - ibm model m
#  - danny

# set alias so the thing also acts as a command

alias fap='~/.faprc $1'

# some colors to choose from

# normal
prompt_black='\[\e[30m\]'
prompt_red='\[\e[31m\]'
prompt_green='\[\e[32m\]'
prompt_yellow='\[\e[33m\]'
prompt_blue='\[\e[34m\]'
prompt_magenta='\[\e[35m\]'
prompt_cyan='\[\e[36m\]'
prompt_white='\[\e[37m\]'

# bold normal
prompt_bblack='\[\033[1;30m\]'
prompt_bred='\[\033[1;31m\]'
prompt_bgreen='\[\033[1;32m\]'
prompt_byellow='\[\033[1;33m\]'
prompt_bblue='\[\033[1;34m\]'
prompt_bmagenta='\[\033[1;35m\]'
prompt_bcyan='\[\033[1;36m\]'
prompt_bwhite='\[\033[1;37m\]'

# intense
prompt_iblack='\[\033[0;90m\]'
prompt_ired='\[\033[0;91m\]'
prompt_igreen='\[\033[0;92m\]'
prompt_iyellow='\[\033[0;93m\]'
prompt_iblue='\[\033[0;94m\]'
prompt_imagenta='\[\033[0;95m\]'
prompt_icyan='\[\033[0;96m\]'
prompt_iwhite='\[\033[0;97m\]'

# bold intense
prompt_biblack='\[\033[1;90m\]'
prompt_bired='\[\033[1;91m\]'
prompt_bigreen='\[\033[1;92m\]'
prompt_biyellow='\[\033[1;93m\]'
prompt_biblue='\[\033[1;94m\]'
prompt_bimagenta='\[\033[1;95m\]'
prompt_bicyan='\[\033[1;96m\]'
prompt_biwhite='\[\033[1;97m\]'

prompt_default_color='\[\e[0m\]'

# prompt pieces

prompt_xtitle='\[\e]0;\w\a\]'
prompt_userhost=$prompt_green'\u@\h'
prompt_cwd=$prompt_yellow'\w'
prompt_time=$prompt_iblue'\t'
prompt_end=$prompt_default_color'$ '
prompt_git='$(git branch &>/dev/null;\
if [ $? -eq 0 ]; then \
  echo "$(echo `git status 2>/dev/null` | grep "nothing to commit" > /dev/null 2>&1; \
  if [ "$?" -eq "0" ]; then \
    # clean repository - nothing to commit
    echo "'$prompt_igreen'"$(__git_ps1 "(%s)"); \
  else \
    # dirty working tree
    echo "'$prompt_ired'"$(__git_ps1 "{%s}"); \
  fi) '$prompt_default_color'"; \
else \
  # Non git prompt
  echo "'$prompt_default_color'"; \
fi)'

# almost completed prompts

prompt_dos='\n\w>'
prompt_nocolor='\n\u@\h \w\n$ '
prompt_full_git=$prompt_time' '$prompt_git''$prompt_userhost':'$prompt_cwd''$prompt_end
prompt_full=$prompt_time' '$prompt_userhost':'$prompt_cwd''$prompt_end
prompt_xterm="$prompt_xtitle""$prompt_full_git"

# select prompt based on terminal variable

case $TERM in
  xterm*|rxvt|screen*|cygwin)
    freaknAwesomePrompt=$prompt_xterm ;;
  linux*|*vt100*|cons25)
    freaknAwesomePrompt=$prompt_full ;;
  *)
    freaknAwesomePrompt=$prompt_nocolor ;;
esac

case $1 in
  off)
    freaknAwesomePrompt=$prompt_full ;;
  git)
    freaknAwesomePrompt=$prompt_full_git ;;
esac

export PS1=$freaknAwesomePrompt
